# configuration.yaml
application:
  port: 8000
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  host_url: "sandbox.smtp.mailtrap.io"
  from: "ram.hdzven@gmail.com"
  username: "cc16782b5fa486"
  password: "926b5352acd1f3"
