# configuration.yaml
application:
  port: 8000
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "https://bulk.api.mailtrap.io"
  sender_email: "mailtrap@demomailtrap.com"
  authorization_token: "275b3b1ac217e288202cc688c436216e"
  timeout_milliseconds: 10000
