# configuration.yaml
application:
  port: 8000
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  api_url: "https://sandbox.api.mailtrap.io"
  api_key: "06317472283fda0dc9965a525aeb539f"
  api_email: "ramses@dagatech.solutions"
